#!/bin/bash

#Automatize the treatment for minifying the code. Used on Linux.
#Need to have uglify installed (if nodejs installed, do: npm -g install uglify )

echo "/*" > gcodetogeometry.min.js
echo "* Generated by PEG.js 0.8.0." >> gcodetogeometry.min.js
echo "*" >> gcodetogeometry.min.js
echo "* http://pegjs.majda.cz/" >> gcodetogeometry.min.js
echo "*/" >> gcodetogeometry.min.js
echo "" >> gcodetogeometry.min.js
echo "/**" >> gcodetogeometry.min.js
echo " * The rest of this module was written by Alex Canales for ShopBotTools, Inc." >> gcodetogeometry.min.js
echo " */" >> gcodetogeometry.min.js
echo "" >> gcodetogeometry.min.js

cat parser.js >> min.js
cat util.js >> min.js
cat lines.js >> min.js
cat gcodetogeometry.js >> min.js
uglify -s min.js -o temp.js
cat temp.js >> gcodetogeometry.min.js
rm min.js temp.js
